[[setting-up]]
== Setting up
Currently, Spek is implemented as a http://junit.org/junit5/[JUnit Platform] *TestEngine*.

You will need to include `org.jetbrains.spek:spek-api` and `org.jetbrains.spek:spek-junit-platform-engine`
in your test classpath. The former is needed during compilation, while the latter during runtime only.

NOTE: For Android projects check <<setting-up-legacy>> section.

=== Gradle
JUnit Platform provides a http://junit.org/junit5/docs/current/user-guide/#running-tests-build[gradle plugin].

[source,groovy,subs="attributes"]
.build.gradle
----
// setup the plugin
buildscript {
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:{junitPlatformVersion}'
    }
}

apply plugin: 'org.junit.platform.gradle.plugin'

junitPlatform {
    filters {
        engines {
            include 'spek'
        }
    }
}

// setup dependencies
dependencies {
    testCompile 'org.jetbrains.spek:spek-api:{version}'
    testRuntime 'org.jetbrains.spek:spek-junit-platform-engine:{version}'
}
----

=== Gradle Kotlin Script
[source,kotlin,subs="attributes"]
.build.gradle.kts
----
import org.gradle.api.plugins.ExtensionAware

import org.junit.platform.gradle.plugin.FiltersExtension
import org.junit.platform.gradle.plugin.EnginesExtension
import org.junit.platform.gradle.plugin.JUnitPlatformExtension

// setup the plugin
buildscript {
    dependencies {
        classpath("org.junit.platform:junit-platform-gradle-plugin:{junitPlatformVersion}")
    }
}

apply {
    plugin("org.junit.platform.gradle.plugin")
}

configure<JUnitPlatformExtension> {
    filters {
        engines {
            include("spek")
        }
    }
}

// setup dependencies
dependencies {
    testCompile("org.jetbrains.spek:spek-api:{version}")
    testRuntime("org.jetbrains.spek:spek-junit-platform-engine:{version}")
}

// extension for configuration
fun JUnitPlatformExtension.filters(setup: FiltersExtension.() -> Unit) {
    when (this) {
        is ExtensionAware -> extensions.getByType(FiltersExtension::class.java).setup()
        else -> throw Exception("${this::class} must be an instance of ExtensionAware")
    }
}
fun FiltersExtension.engines(setup: EnginesExtension.() -> Unit) {
    when (this) {
        is ExtensionAware -> extensions.getByType(EnginesExtension::class.java).setup()
        else -> throw Exception("${this::class} must be an instance of ExtensionAware")
    }
}
----

=== Maven

JUnit provides support for http://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven[Maven].

[source,xml,subs="attributes+"]
.pom.xml
----
...
<dependency>
  <groupId>org.jetbrains.spek</groupId>
  <artifactId>spek-api</artifactId>
  <version>{version}</version>
  <type>pom</type>
</dependency>
----

[[setting-up-legacy]]
== Using Spek with JUnit 4
JUnit 4 based runner is still supported via http://junit.org/junit5/[JUnit Platform]. You will need the following dependencies on the test classpath:

- `org.jetbrains.spek:spek-api:{version}`
- `org.jetbrains.spek:spek-junit-platform-engine:{version}`
- `org.junit.platform:junit-platform-runner:{junitPlatformVersion}`

The finally, annotate your specs with `@RunWith(JUnitPlatform::class)`.

[source,kotlin]
.CalculatorSpec.kt
----
@RunWith(JUnitPlatform::class)
class CalculatorSpec: Spek({
    ...
})
----

IMPORTANT: As mentioned in the <<ide-support>> section, the IDEA plugin won't work if you're using the JUnit 4 runner.


