[[setting-up]]
== Setting up
Currently, Spek is implemented as a http://junit.org/junit5/[JUnit Platform] *TestEngine*.

You will need to include `org.jetbrains.spek:spek-api` and `org.jetbrains.spek:spek-junit-platform-engine`
in your test classpath. The former is needed during compilation, while the latter during runtime only.

NOTE: For Android projects check <<setting-up-legacy>> section.

=== Gradle
JUnit Platform provides a http://junit.org/junit5/docs/current/user-guide/#running-tests-build[gradle plugin].

[source,groovy,subs="attributes"]
.build.gradle
----
// setup the plugin
buildscript {
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:{junitPlatformVersion}'
    }
}

apply plugin: 'org.junit.platform.gradle.plugin'

junitPlatform {
    filters {
        engines {
            include 'spek'
        }
    }
}

repositories {
    maven { url "http://dl.bintray.com/jetbrains/spek" }
}

// setup dependencies
dependencies {
    testCompile 'org.jetbrains.spek:spek-api:{version}'
    testRuntime 'org.jetbrains.spek:spek-junit-platform-engine:{version}'
}
----

=== Gradle Kotlin Script
[source,kotlin,subs="attributes"]
.build.gradle.kts
----
import org.gradle.api.plugins.ExtensionAware

import org.junit.platform.gradle.plugin.FiltersExtension
import org.junit.platform.gradle.plugin.EnginesExtension
import org.junit.platform.gradle.plugin.JUnitPlatformExtension

// setup the plugin
buildscript {
    dependencies {
        classpath("org.junit.platform:junit-platform-gradle-plugin:{junitPlatformVersion}")
    }
}

apply {
    plugin("org.junit.platform.gradle.plugin")
}

configure<JUnitPlatformExtension> {
    filters {
        engines {
            include("spek")
        }
    }
}

// setup dependencies
dependencies {
    testCompile("org.jetbrains.spek:spek-api:{version}")
    testRuntime("org.jetbrains.spek:spek-junit-platform-engine:{version}")
}

// extension for configuration
fun JUnitPlatformExtension.filters(setup: FiltersExtension.() -> Unit) {
    when (this) {
        is ExtensionAware -> extensions.getByType(FiltersExtension::class.java).setup()
        else -> throw Exception("${this::class} must be an instance of ExtensionAware")
    }
}
fun FiltersExtension.engines(setup: EnginesExtension.() -> Unit) {
    when (this) {
        is ExtensionAware -> extensions.getByType(EnginesExtension::class.java).setup()
        else -> throw Exception("${this::class} must be an instance of ExtensionAware")
    }
}
----

=== Using later versions of Kotlin
If you are using a version of Kotlin that is different than the one used by Spek, you will want to exclude
the group in your dependency definition.

[source,groovy,subs="attributes"]
.build.gradle
----
dependencies {

    // your application's newer version of Kotlin
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    testCompile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    testCompile ('org.jetbrains.spek:spek-api:{version}') {
        exclude group: 'org.jetbrains.kotlin'
    }
    testRuntime ('org.jetbrains.spek:spek-junit-platform-engine:{version}') {
        exclude group: 'org.junit.platform'
        exclude group: 'org.jetbrains.kotlin'
    }
}
----

=== Maven

JUnit provides support for http://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven[Maven].

[source,xml,subs="attributes+"]
.pom.xml
----
...
<dependency>
  <groupId>org.jetbrains.spek</groupId>
  <artifactId>spek-api</artifactId>
  <version>{version}</version>
  <type>pom</type>
</dependency>
----

[[setting-up-legacy]]
== Using Spek with JUnit 4
JUnit 4 based runner is still supported via http://junit.org/junit5/[JUnit Platform]. You will need the following dependencies on the test classpath:

- `org.jetbrains.spek:spek-api:{version}`
- `org.jetbrains.spek:spek-junit-platform-engine:{version}`
- `org.junit.platform:junit-platform-runner:{junitPlatformVersion}`

The finally, annotate your specs with `@RunWith(JUnitPlatform::class)`.

[source,kotlin]
.CalculatorSpec.kt
----
@RunWith(JUnitPlatform::class)
class CalculatorSpec: Spek({
    ...
})
----

IMPORTANT: As mentioned in the <<ide-support>> section, the IDEA plugin won't work if you're using the JUnit 4 runner.



[[setting-up-android]]
== Setting up Android
JUnit Platform does not support android projects out of the box, we need to use https://github.com/mannodermaus/android-junit5.

[source,groovy,subs="attributes"]
.build.gradle
----
buildscript {
    ...

    // 1. Add the android-junit5 Gradle plugin as a classpath dependency
    dependencies {
        classpath "de.mannodermaus.gradle.plugins:android-junit5:${junitPlatformVersion}"
    }
}
----


[source,groovy,subs="attributes"]
.app/build.gradle
----
...
// 2. Apply the android-junit5 plugin alongside your app's plugins
apply plugin: "de.mannodermaus.android-junit5"

android {
    ...
    // 3. Extend the Java source set with the Kotlin folders
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }
}

// 4. Configure spek's TestEngine to be detected by JUnit 5
junitPlatform {
    filters {
        engines {
            include 'spek'
        }
    }
}

dependencies {
    ...
    // 5. Add the dependencies on spek & its required co-dependencies to the test scope
    testImplementation("org.jetbrains.spek:spek-api:${version}") {
        exclude group: "org.jetbrains.kotlin"
    }
    testImplementation("org.jetbrains.spek:spek-junit-platform-engine:${version}") {
        exclude group: "org.junit.platform"
        exclude group: "org.jetbrains.kotlin"
    }
    testImplementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    // 6. If you want to use @RunWith(...) a.k.a JUnit 4
    testImplementation "org.junit.platform:junit-platform-runner:${junitPlatformVersion}"
}

// 7. Finally, configure AS to copy over Kotlin classes for each build type to where the IDE can pick them up
afterEvaluate {
    android.buildTypes.each {
        def name = it.name

        def copyTestTask = project.task(type: Copy, "copyKotlin${name.capitalize()}UnitTestClasses") {
            from "build/tmp/kotlin-classes/${name}UnitTest"
            into "build/intermediates/classes/test/$name"
        }
        project.tasks.getByName("compile${name.capitalize()}UnitTestKotlin").finalizedBy copyTestTask

        def copyMainTask = project.task(type: Copy, "copyKotlin${name.capitalize()}Classes") {
            from "build/tmp/kotlin-classes/${name}"
            into "build/intermediates/classes/$name"
        }
        project.tasks.getByName("compile${name.capitalize()}Kotlin").finalizedBy copyMainTask
    }
}
----
