== Writing Specifications

=== Assertion Framework
Spek doesn't have any built-in assertions, luckily there are several libraries in the wild that do. Below are several suggestions:

- `org.jetbrains.kotlin:kotlin-test`
- https://github.com/npryce/hamkrest[HamKrest]
- https://github.com/winterbe/expekt[Expekt]
- https://github.com/MarkusAmshove/Kluent[Kluent]

=== Basic Structure

Your specifications need to inherit from the `org.jetbrains.spek.api.Spek` base class.

[source,kotlin]
.SimpleSpec.kt
----
class SimpleSpec: Spek({
    describe("a calculator") {
        val calculator = SampleCalculator()

        it("should return the result of adding the first number to the second number") {
            val sum = calculator.sum(2, 4)
            assertEquals(6, sum)
        }

        it("should return the result of subtracting the second number from the first number") {
            val subtract = calculator.subtract(4, 2)
            assertEquals(2, subtract)
        }
    }
})
----

The `it` method creates a `test` scope, which is equivalent to a test method in JUnit. While the `describe` method creates
a `group` scope, which can contain nested `test` and/or `group` scopes. Spek supports arbitrary number of nested scopes for
better grouping of your tests.

Aside from `describe`, Spek also provides `given`, `on` and `context` to create `group` scopes.

IMPORTANT: Due to how Spek is structured, `group` scopes are eagerly evaluated during the discovery phase. Any logic that
needs to be evaluated before and/or after `test` scopes should be done using fixtures, which will be discussed in the next section.

=== Fixtures

Spek provides `beforeEachTest` and `afterEachTest` fixtures, which allows running arbitrary code before and after a `test`, respectively. Every
`group` scope can declare an arbitrary number of fixtures, the order they are executed is based on the order they are declared.

[source,kotlin]
.FixtureSpec.kt
----
class FixtureSpec: Spek({
    describe("a group") {
        beforeEachTest {
            ...
        }

        context("a nested group") {

            beforeEachTest {
                ...
            }

            beforeEachTest {
                ...
            }

            it ("should work") { ... }
        }

        it("do something") { ... }

        afterEachTest {
            ...
        }
    }
})
----

=== Ignoring tests
Each scope method have a variant prefixed with `x` (e.g. `xdescribe`, `xit`, etc...), which will Spek ignore when executing the spec.

=== Subjects
NOTE: This feature is currently experimental.

Normally you will only have a single class as the https://en.wikipedia.org/wiki/System_under_test[SUT]. Spek provides an idiomatic way
of writing this types of tests and removing a lot of boilerplate code.

[source,kotlin]
.SimpleCalculatorSpec.kt
----
class SimpleCalculatorSpec: SubjectSpek<Calculator>({
    subject { Calculator() } <1>

    it("should return the result of adding the first number to the second number") {
        assertEquals(6, subject.sum(2, 4)) <2>
    }

    it("should return the result of subtracting the second number from the first number") {
        assertEquals(2, subject.subtract(4, 2)) <2>
    }
})
----
<1> Tell Spek how to instantiate the subject, in this case a `Calculator`. This will be invoked for every `test` scope, which means each `test` scope will have a unique instance.
<2> Use `subject` to access the instance of the subject.

==== Shared Subjects
This feature is useful when testing subclasses, removing the need of duplicating test code.

Given `AdvancedCalculator` which is a subclass of `Calculator`, a typical test will look like the following:
[source,kotlin]
.AdvancedCalculatorSpec.kt
----
class AdvancedCalculatorSpec: SubjectSpek<AdvancedCalculator>({
    subject { AdvancedCalculator() }

    itBehavesLike(SimpleCalculatorSpec::class)

    describe("pow") {
        it("should return the power of base raise to exponent") {
            assertEquals(subject.pow(2, 2), 4)
        }
    }
})
----

This will include all scopes declared in `SimpleCalculatorSpec`.
