== Writing Specifications

=== Assertion Framework
Spek doesn't have any built-in assertions, luckily there are several libraries in the wild that do. Below are several suggestions:

- `org.jetbrains.kotlin:kotlin-test` (make sure to use the `-ea` VM option in your Spek run configuration when using this one or Kotlin's built in assertions)
- https://github.com/npryce/hamkrest[HamKrest]
- https://github.com/winterbe/expekt[Expekt]
- https://github.com/MarkusAmshove/Kluent[Kluent]

=== Scopes
Spek provides 3 types of scopes, which are used to define your spec.

==== Test
Equivalent to test methods in JUnit, normally all assertions are done in this scope. Use `it` to define a test scope.

==== Group
May contain an arbitrary number of nested scopes for better grouping of your tests.

==== Action
Represents an action that will be performed and may contain any number of test scopes. You can think of each `test` as an assertion to
validate the expected behaviour of the action performed.

=== Basic Structure

Your specifications need to inherit from the `org.jetbrains.spek.api.Spek` base class.

[source,kotlin]
.SimpleSpec.kt
----
object SimpleSpec: Spek({
    describe("a calculator") {
        val calculator = SampleCalculator()

        on("addition") {
            val sum = calculator.sum(2, 4)

            it("should return the result of adding the first number to the second number") {
                assertEquals(6, sum)
            }
        }

        on("subtraction") {
            val subtract = calculator.subtract(4, 2)

            it("should return the result of subtracting the second number from the first number") {
                assertEquals(2, subtract)
            }
        }
    }
})
----

Aside from `describe`, Spek also provides `given` and `context` to create `group` scopes.

IMPORTANT: Due to how Spek is structured, `group` scopes are eagerly evaluated during the discovery phase. Any logic that
needs to be evaluated before and/or after `test` scopes should be done using fixtures, which will be discussed in the next section.

=== Fixtures
Spek allows running arbitrary code before and after a `group` and `test` is executed.

NOTE: You can't declare fixtures within `action` scopes.

[source,kotlin]
.FixtureSpec.kt
----
object FixtureSpec: Spek({
    describe("a group") {
        beforeGroup {
            ...
        }

        beforeEachTest {
            ...
        }

        context("a nested group") {

            beforeEachTest {
                ...
            }

            beforeEachTest {
                ...
            }

            it ("should work") { ... }
        }

        it("do something") { ... }

        afterEachTest {
            ...
        }

        afterGroup {
            ...
        }
    }
})
----

=== Ignoring tests
Each scope method have a variant prefixed with `x` (e.g. `xdescribe`, `xit`, etc...), which will Spek ignore when executing the spec.

=== Subjects
NOTE: This feature is currently experimental.

Normally you will only have a single class as the https://en.wikipedia.org/wiki/System_under_test[SUT]. Spek provides an idiomatic way
of writing this types of tests and removing a lot of boilerplate code.

[source,kotlin]
.SimpleCalculatorSpec.kt
----
object SimpleCalculatorSpec: SubjectSpek<Calculator>({
    subject { Calculator() } <1>

    it("should return the result of adding the first number to the second number") {
        assertEquals(6, subject.sum(2, 4)) <2>
    }

    it("should return the result of subtracting the second number from the first number") {
        assertEquals(2, subject.subtract(4, 2)) <2>
    }
})
----
<1> Tell Spek how to instantiate the subject, in this case a `Calculator`. This will be invoked for every `test` scope, which means each `test` scope will have a unique instance.
<2> Use `subject` to access the instance of the subject.

==== Shared Subjects
This feature is useful when testing subclasses, removing the need of duplicating test code.

Given `AdvancedCalculator` which is a subclass of `Calculator`, a typical test will look like the following:
[source,kotlin]
.AdvancedCalculatorSpec.kt
----
object AdvancedCalculatorSpec: SubjectSpek<AdvancedCalculator>({
    subject { AdvancedCalculator() }

    itBehavesLike(SimpleCalculatorSpec)

    describe("pow") {
        it("should return the power of base raise to exponent") {
            assertEquals(subject.pow(2, 2), 4)
        }
    }
})
----

This will include all scopes declared in `SimpleCalculatorSpec`.

=== Example based tests aka table based tests aka parametrized tests

NOTE: This feature is currently experimental.

Sometimes you have tests that looks a lot alike. They differ just by some variables.
Imagine you have tests like :

[source,kotlin]
.ExampleBasedSpec.kt
----
object ExampleBasedSpec: Spek({
    describe("a calculator's addition") {
        val calculator = Calculator()
        it("should return the result of adding 2 to 4") {
            assertEquals(6, calculator.add(2, 4))
        }
        it("should return the result of adding 3 to 3") {
            assertEquals(6, calculator.add(3, 3))
        }
    }
})
----

You can see that you have that looks a lot alike except for the inputs. With examples based tests, you can then write
 it that way :

[source,kotlin]
.ExampleBasedSpec.kt
----
object ExampleBasedSpec: Spek({
    describe("a calculator") {
        val calculator = Calculator()
        with(
            example(2, 4),
            example(3, 3)
        ) { a, b ->
            it("should return the result of adding two numbers together") {
                assertEquals(6, calculator.add(a, b))
            }
        }
    }
})
----

You can then easily add new examples ! The best part of all : the test can have a name much closer to the real
business !