name: CI
on:
  push:
    branches:
      - 2.x
      - 2.0.x
    tags:
      - '*'

jobs:
  deploy_spek2:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            arguments: spek-dsl:publish spek-runtime:publish spek-runner-junit5:publish --stacktrace -PexcludeIdePlugins
          - os: windows-latest
            arguments: spek-dsl:publish spek-runtime:publish --stacktrace -PexcludeIdePlugins
          - os: macos-latest
            arguments: spek-dsl:publish spek-runtime:publish --stacktrace -PexcludeIdePlugins
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: ${{ matrix.arguments }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_SIGNING_KEY: ${{ secrets.OSSRH_SIGNING_KEY }}
          OSSRH_SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}

  deploy_ij_plugin:
    strategy:
      fail-fast: false
      matrix:
        ij_sdk: [IJ193, IJ201, IJ202, IJ203, IJ211, IJ212, IJ213, IJ233]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: spek-ide-plugin-intellij-idea:publishPlugin -Pij.version=${{ matrix.ij_sdk }} --stacktrace
        env:
          HUB_API_TOKEN: ${{ secrets.HUB_API_TOKEN }}

  deploy_as_plugin:
    strategy:
      fail-fast: false
      matrix:
        as_sdk: [AS36, AS40, AS41, AS42]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: spek-ide-plugin-android-studio:publishPlugin -Pas.version=${{ matrix.as_sdk }} --stacktrace
        env:
          HUB_API_TOKEN: ${{ secrets.HUB_API_TOKEN }}
