[[setting-up]]
== Setting up
NOTE: For Android projects check <<setting-up-android>> section.

You will need to include `org.jetbrains.spek:spek-api` and `org.jetbrains.spek:spek-junit-platform-engine`
in your test classpath. The former is needed during compilation, while the latter during runtime only.

=== Gradle
Thankfully JUnit Platform provides a http://junit.org/junit5/docs/current/user-guide/#running-tests-build[gradle plugin] that will make our life easier.

[source,groovy,subs="attributes+"]
.build.gradle
----
// setup the plugin
buildscript {
    classpath 'org.junit.platform:junit-platform-gradle-plugin:<version>'
}

apply plugin: 'org.junit.platform.gradle.plugin'

junitPlatform {
    engines {
        include 'spek'
    }
}

// setup dependencies
dependencies {
    testCompile 'org.jetbrains.spek:spek-api:1.0.89'
    testRuntime 'org.jetbrains.spek:spek-junit-platform-engine:1.0.89'
}
----

=== Gradle Kotlin Script
[source,kotlin,subs="attributes+"]
.build.gradle.kts
----
import org.gradle.api.plugins.ExtensionAware

import org.junit.platform.gradle.plugin.EnginesExtension
import org.junit.platform.gradle.plugin.JUnitPlatformExtension

// setup the plugin
buildscript {
    dependencies {
        classpath("org.junit.platform:junit-platform-gradle-plugin:<version>")
    }
}

apply {
    plugin("org.junit.platform.gradle.plugin")
}

configure<JUnitPlatformExtension> {
    engines {
        include("spek")
    }
}

// setup dependencies
dependencies {
    testCompile("org.jetbrains.spek:spek-api:1.0.89")
    testRuntime("org.jetbrains.spek:spek-junit-platform-engine:1.0.89")
}

// extension for configuration
fun JUnitPlatformExtension.engines(setup: EnginesExtension.() -> Unit) {
    when (this) {
        is ExtensionAware -> extensions.getByType(EnginesExtension::class.java).setup()
        else -> throw Exception("${this::class} must be an insance of ExtensionAware")
    }
}
----

=== Maven

JUnit provides support for http://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven[Maven].

[source,xml]
.pom.xml
----
...
<dependency>
  <groupId>org.jetbrains.spek</groupId>
  <artifactId>spek-api</artifactId>
  <version>1.0.89</version>
  <type>pom</type>
</dependency>
----

[[setting-up-android]]
== Setting up for Android
The JUnit Platform gradle plugin currently doesn't support Android projects (see https://github.com/junit-team/junit5/issues/204), but thankfully
a JUnit 4 based runner is provided.

First, add the required dependencies.
[source,groovy,subs="attributes+"]
.build.gradle
----
// setup dependencies
dependencies {
    testCompile 'org.jetbrains.spek:spek-api:1.0.89'
    testCompile 'org.junit.platform:junit-platform-runner:1.0.0-M2'
}
----

Finally make sure your specs are annotated with `@RunWith(JUnitPlatform::class)`.

[source,kotlin]
.CalculatorSpec.kt
----
@RunWith(JUnitPlatform::class)
class CalculatorSpec: Spek({
    ...
})
----

As mentioned in the <<ide-support>> section, the IDEA plugin won't work if you're using the JUnit 4 runner.


